---
- hosts: localhost
  become: yes
  tasks:
    - name: Load vars
      include_vars:
        file: packages.yml
    - name: Install extra packages
      apt:
        update_cache: true
        cache_valid_time: 86400 # 1 day
        name: "{{ packages }}"
        state: latest
    - name: Add snap to path
      lineinfile:
        dest: /etc/environment
        line: "PATH=$PATH:/snap/bin"
    - name: Enable snapd
      service:
        name: snapd
        enabled: yes
        state: started
    - name: Enable apparmor
      service:
        name: apparmor
        enabled: yes
        state: started
    - name: Install snap core
      community.general.snap:
        name: core
        state: present
    - name: Prep for VS Code install
      apt:
        name:
          - curl
          - gpg
          - gnupg2
          - software-properties-common
          - apt-transport-https
        state: latest
    - name: Check for MS GPG key
      stat:
        path: /etc/apt/trusted.gpg.d/microsoft.gpg
      register: ms_gpg_key
    - name: Download MS GPG key
      get_url:
        url: https://packages.microsoft.com/keys/microsoft.asc
        dest: /tmp/microsoft.asc
      when: not ms_gpg_key.stat.exists
    - name: De-armor MS GPG key
      command: gpg --dearmor /tmp/microsoft.asc > /tmp/microsoft.gpg
      delegate_to: localhost
      when: not ms_gpg_key.stat.exists
    - name: Import MS GPG key
      command: mv /tmp/microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
      when: not ms_gpg_key.stat.exists
    - name: Check for VSCode repo
      stat:
        path: /etc/apt/sources.list.d/vscode.list
      register: vscode_repo
    - name: Add VSCode repo
      lineinfile:
        path: /etc/apt/sources.list.d/vscode.list
        line: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        create: yes
        state: present
          #      command: echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list
      delegate_to: localhost
      when: not vscode_repo.stat.exists
    - name: Update and install VS Code
      apt:
        update_cache: true
        name:
          - code
        state: latest
    - name: Check if Discord is installed
      command: dpkg-query -W discord
      delegate_to: localhost
      register: discord_installed
      failed_when: discord_installed.rc > 1
      changed_when: discord_installed.rc == 1
      ignore_errors: true
    - name: Install discord
      community.general.snap:
        name: discord
        state: present
      when: discord_installed.rc == 1
    - name: Snap connect discord:system-observe
      command: snap connect discord:system-observe
      delegate_to: localhost
      when: discord_installed.rc == 1
    - name: Check if authy installed
      command: dpkg-query -W authy
      delegate_to: localhost
      register: authy_installed
      failed_when: authy_installed.rc > 1
      changed_when: authy_installed.rc == 1
      ignore_errors: true
    - name: Install authy
      community.general.snap:
        name: authy
        state: present
      when: authy_installed.rc ==1

